"use client"

import { AtSymbolIcon, ChevronLeftIcon } from "@heroicons/react/24/solid"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { useState } from "react"
import {
  SeatFormStateContext,
  SEAT_FORM_STATE,
} from "./(trips)/hooks/useSeatForm"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  params: {
    tripId: string
  }
}) {
  const [form, setForm] = useState(SEAT_FORM_STATE)
  const router = useRouter()

  return (
    <html lang="es">
      <body className={`${inter.className} mx-auto min-h-screen max-w-md`}>
        <SeatFormStateContext.Provider value={{ form, setForm }}>
          <div className="my-4 flex justify-between">
            <button type="button" onClick={() => router.back()} className="p-1">
              <ChevronLeftIcon className="h-6 w-6 text-violet-900" />
            </button>
            <Link href="mis-viajes" className="p-1">
              <AtSymbolIcon className="h-6 w-6 text-violet-900" />
            </Link>
          </div>
          {children}
        </SeatFormStateContext.Provider>
      </body>
    </html>
  )
}
